steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gcloud compute ssh samanerendra@inference-instance \
      --zone='us-central1-a' \
      --project='intelligate-security-system' \
      --quiet \
      --command="\
         source /home/samanerendra/IntelliGate/bin/activate && \
         cd /home/samanerendra/Edge-AI-CW && \
         git pull && \
         python3 capture_video_and_predict_cloud.py"
timeout: '1200s'  # Adjust timeout to fit your script's needs